import { expect, test } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { contrastRatio, meetsAA, CONNECTA, buildConnecta } from "./brand";

test("contrastRatio computes the WCAG ratio for black on white", () => {
  expect(contrastRatio("#000000", "#ffffff")).toBeCloseTo(21, 0);
});

test("contrastRatio is symmetric", () => {
  const a = contrastRatio("#705838", "#fbf9f4");
  const b = contrastRatio("#fbf9f4", "#705838");
  expect(a).toBeCloseTo(b, 5);
});

test("meetsAA rejects a low-contrast muted gray on near-white", () => {
  expect(meetsAA("#a8a29e", "#fbf9f4")).toBe(false);
});

test("meetsAA accepts body-safe ink on near-white", () => {
  expect(meetsAA("#2a2724", "#fbf9f4")).toBe(true);
});

test("meetsAA is more permissive for large text", () => {
  expect(meetsAA("#8a8178", "#fbf9f4", true)).toBe(true);
  expect(meetsAA("#8a8178", "#fbf9f4", false)).toBe(false);
});

test("CONNECTA brand constant carries the product name", () => {
  expect(CONNECTA.name).toBe("Connecta");
});

test("CONNECTA brand constant carries the tagline", () => {
  expect(CONNECTA.tagline).toBe("tap.connect.grow.");
});

test("buildConnecta falls back to connecta.example when NEXT_PUBLIC_APP_URL is unset", () => {
  expect(buildConnecta({}).domain).toBe("connecta.example");
});

test("buildConnecta derives the domain from NEXT_PUBLIC_APP_URL when set", () => {
  expect(buildConnecta({ NEXT_PUBLIC_APP_URL: "https://app.example.com" }).domain).toBe(
    "app.example.com"
  );
});

test("buildConnecta derives the domain from a NEXT_PUBLIC_APP_URL that has no protocol", () => {
  expect(buildConnecta({ NEXT_PUBLIC_APP_URL: "app.example.com/" }).domain).toBe(
    "app.example.com"
  );
});

test("buildConnecta defaults supportEmail to support@<domain>", () => {
  expect(buildConnecta({ NEXT_PUBLIC_APP_URL: "https://app.example.com" }).supportEmail).toBe(
    "support@app.example.com"
  );
});

test("buildConnecta lets SUPPORT_EMAIL override the support inbox independently of the domain", () => {
  expect(
    buildConnecta({ NEXT_PUBLIC_APP_URL: "https://app.example.com", SUPPORT_EMAIL: "help@realcompany.com" })
      .supportEmail
  ).toBe("help@realcompany.com");
});

// Directories intentionally NOT scanned:
// - node_modules, .next, .git: not our source.
// - .firecrawl, .superpowers: tool-generated caches, not committed product docs.
// - docs (specifically docs/superpowers/plans/*) and qoder_plans: historical
//   plan/analysis records generated by past agent sessions. They document
//   what happened at the time and are deliberately left as-is rather than
//   rewritten after the fact — see the rename-completion report.
const SKIP_DIRS = ["node_modules", ".next", ".git", ".vercel", "docs", ".firecrawl", ".superpowers", "qoder_plans"];

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.includes(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    // Source (.ts/.tsx/.css) AND committed product docs/manifests (.md/.json)
    // — the stale brand name lived in package.json and root .md docs too,
    // not just source files, so both must be covered for this test to mean
    // anything.
    else if (/\.(tsx?|css|md|json)$/.test(entry)) acc.push(full);
  }
  return acc;
}

// Covers all three retired brand names — this product has been renamed three
// times (Tapfolio -> Herald -> SigmaTap -> Connecta) and none should
// resurface. Built from fragments so this file does not match its own check.
const STALE_BRAND = new RegExp(
  [
    ["tap", "folio"].join(""),
    ["her", "ald"].join(""),
    ["sigma", "tap"].join(""),
  ].join("|"),
  "i"
);

// Justified exceptions: the old name survives here on purpose. Two flavors:
//  1. NOT user-facing brand copy — a real, live infrastructure identifier or
//     a client-storage key whose value must stay byte-identical to keep
//     working. Renaming these would silently break runtime behavior rather
//     than just relabel text.
//  2. Rename-history documentation — comments that talk *about* a retired
//     name (e.g. "renamed from Tapfolio") rather than render it as brand
//     copy. Kept as prose, per this project's convention of updating rename
//     history to remain accurate rather than deleting it.
//
// Line-scoped (exact-string), not whole-file: each entry is the literal text
// of the ONE line that's allowed to say an old name. Any other line in the
// same file — including a new offender introduced later — still fails the
// check. (A prior version of this allowlist skipped the entire file, which
// is how app/admin/factory/page.tsx was able to print an unrelated,
// unowned domain that nobody caught until a full-branch audit; see the
// final-review-fixes report.)
// Every previous rename had to freeze literals that could not change without
// breaking runtime behaviour: localStorage keys already written to real
// browsers, and deployment hosts printed on shipped NFC cards. A purge on
// 2026-08-31 removed every account but one and left a single test card, so
// no live population sits behind either. Both freezes were lifted with the
// Connecta rename and this allowlist is now empty. Keep it that way: a new
// entry here means a retired brand name is shipping to users again.
const INFRA_EXCEPTIONS: Record<string, string[]> = {};

test("no user-facing source file still says either retired brand name", () => {
  const selfPath = join("lib", "brand.test.ts");
  const offenders: string[] = [];
  for (const file of walk(process.cwd())) {
    const rel = file.replace(process.cwd(), "").replace(/^[\\/]/, "");
    if (rel === selfPath) continue;
    const allowedLines = INFRA_EXCEPTIONS[rel] ?? [];
    const content = readFileSync(file, "utf8");
    const remaining = content
      .split("\n")
      .filter((line) => !allowedLines.some((allowed) => line.trim() === allowed))
      .join("\n");
    if (STALE_BRAND.test(remaining)) offenders.push(rel);
  }
  expect(offenders, `stale brand in:\n${offenders.join("\n")}`).toEqual([]);
});

// Guard against reintroducing the bug this project has now hit twice: 48 JSX
// call sites hardcoded the CURRENT brand name ("Herald") as a string literal
// instead of importing HERALD from this module, which made the first rename
// (Tapfolio -> Herald) an expensive repo-wide sweep instead of a one-line
// edit here. Both later renames (Herald -> SigmaTap, SigmaTap -> Connecta)
// stayed cheap because that migration had already happened — this test now
// protects Connecta the same way, and fails the day someone types a new
// `>Connecta<` or `"...Connecta..."` into app/** or components/** instead of
// `{CONNECTA.name}`.
//
// `\bConnecta\b` is deliberately case-sensitive with word boundaries: it does
// NOT match `ConnectaMark` / `buildConnecta` (no boundary between "Connecta"
// and the adjoining word character) or `CONNECTA` / `connecta-mark.svg` /
// `--connecta-brand` (wrong case) — those are legitimate, not brand-string
// leaks. Doc comments must say "the product" rather than the bare name, so
// that no allowlist is needed at all.
const CURRENT_BRAND_WORD = /\bConnecta\b/;

// convex/** renders customer-facing brand copy (order-confirmation emails,
// lead notifications — see convex/email.ts) and lib/** is where the brand
// constant itself lives, so both need the same guard as app/** and
// components/**: a hardcoded brand string anywhere in either is exactly
// the bug this test exists to catch.
const NEW_BRAND_STRING_SCAN_DIRS = ["app", "components", "convex", "lib"];

const NEW_BRAND_STRING_EXCEPTIONS: Record<string, string[]> = {};

// lib/brand.ts is the single source of truth this whole guard protects: it
// necessarily defines `name: "Connecta"` once, by design, so every OTHER
// file can import CONNECTA.name instead of hardcoding the string. Excluding
// it here is a structural fact about where the constant lives — the same
// shape of exception `selfPath` already grants this test file itself in
// the STALE_BRAND test above — not a "the old name is allowed to leak
// here" carve-out, so it does not go in NEW_BRAND_STRING_EXCEPTIONS.
// This test file is excluded for the same reason: its own assertions and
// comments necessarily quote "Connecta" to describe what the guard does.
const NEW_BRAND_STRING_STRUCTURALLY_EXEMPT = [
  join("lib", "brand.ts"),
  join("lib", "brand.test.ts"),
];

test("no new hardcoded occurrence of the current brand name in app/**, components/**, convex/**, or lib/**", () => {
  const offenders: string[] = [];
  for (const dir of NEW_BRAND_STRING_SCAN_DIRS) {
    const root = join(process.cwd(), dir);
    for (const file of walk(root)) {
      if (!/\.(tsx?|css)$/.test(file)) continue;
      const rel = file.replace(process.cwd(), "").replace(/^[\\/]/, "");
      if (NEW_BRAND_STRING_STRUCTURALLY_EXEMPT.includes(rel)) continue;
      const allowedLines = NEW_BRAND_STRING_EXCEPTIONS[rel] ?? [];
      const content = readFileSync(file, "utf8");
      const remaining = content
        .split("\n")
        .filter((line) => !allowedLines.some((allowed) => line.trim() === allowed))
        .join("\n");
      if (CURRENT_BRAND_WORD.test(remaining)) offenders.push(rel);
    }
  }
  expect(offenders, `hardcoded "Connecta" outside CONNECTA constant in:\n${offenders.join("\n")}`).toEqual([]);
});
