import { expect, test } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { contrastRatio, meetsAA, CONNECTA, buildConnecta } from "./brand";

test("contrastRatio computes the WCAG ratio for black on white", () => {
  expect(contrastRatio("#000000", "#ffffff")).toBeCloseTo(21, 0);
});

test("contrastRatio is symmetric", () => {
  const a = contrastRatio("#705838", "#fbf9f4");
  const b = contrastRatio("#fbf9f4", "#705838");
  expect(a).toBeCloseTo(b, 5);
});

test("meetsAA rejects a low-contrast muted gray on near-white", () => {
  expect(meetsAA("#a8a29e", "#fbf9f4")).toBe(false);
});

test("meetsAA accepts body-safe ink on near-white", () => {
  expect(meetsAA("#2a2724", "#fbf9f4")).toBe(true);
});

test("meetsAA is more permissive for large text", () => {
  expect(meetsAA("#8a8178", "#fbf9f4", true)).toBe(true);
  expect(meetsAA("#8a8178", "#fbf9f4", false)).toBe(false);
});

test("CONNECTA brand constant carries the product name", () => {
  expect(CONNECTA.name).toBe("Connecta");
});

test("CONNECTA brand constant carries the tagline", () => {
  expect(CONNECTA.tagline).toBe("tap.connect.grow.");
});

test("buildConnecta falls back to connecta.example when NEXT_PUBLIC_APP_URL is unset", () => {
  expect(buildConnecta({}).domain).toBe("connecta.example");
});

test("buildConnecta derives the domain from NEXT_PUBLIC_APP_URL when set", () => {
  expect(buildConnecta({ NEXT_PUBLIC_APP_URL: "https://app.example.com" }).domain).toBe(
    "app.example.com"
  );
});

test("buildConnecta derives the domain from a NEXT_PUBLIC_APP_URL that has no protocol", () => {
  expect(buildConnecta({ NEXT_PUBLIC_APP_URL: "app.example.com/" }).domain).toBe(
    "app.example.com"
  );
});

test("buildConnecta defaults supportEmail to support@<domain>", () => {
  expect(buildConnecta({ NEXT_PUBLIC_APP_URL: "https://app.example.com" }).supportEmail).toBe(
    "support@app.example.com"
  );
});

test("buildConnecta lets SUPPORT_EMAIL override the support inbox independently of the domain", () => {
  expect(
    buildConnecta({ NEXT_PUBLIC_APP_URL: "https://app.example.com", SUPPORT_EMAIL: "help@realcompany.com" })
      .supportEmail
  ).toBe("help@realcompany.com");
});

// Directories intentionally NOT scanned:
// - node_modules, .next, .git: not our source.
// - .firecrawl, .superpowers: tool-generated caches, not committed product docs.
// - docs (specifically docs/superpowers/plans/*) and qoder_plans: historical
//   plan/analysis records generated by past agent sessions. They document
//   what happened at the time and are deliberately left as-is rather than
//   rewritten after the fact — see the rename-completion report.
const SKIP_DIRS = ["node_modules", ".next", ".git", ".vercel", "docs", ".firecrawl", ".superpowers", "qoder_plans"];

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.includes(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    // Source (.ts/.tsx/.css) AND committed product docs/manifests (.md/.json)
    // — the stale brand name lived in package.json and root .md docs too,
    // not just source files, so both must be covered for this test to mean
    // anything.
    else if (/\.(tsx?|css|md|json)$/.test(entry)) acc.push(full);
  }
  return acc;
}

// Covers BOTH retired brand names — this product has been renamed twice
// (Tapfolio -> Herald -> SigmaTap) and neither old name should resurface.
// Built from fragments so this file does not match its own check.
const STALE_BRAND = new RegExp(
  ["tap", "folio"].join("") + "|" + ["her", "ald"].join(""),
  "i"
);

// Justified exceptions: the old name survives here on purpose. Two flavors:
//  1. NOT user-facing brand copy — a real, live infrastructure identifier or
//     a client-storage key whose value must stay byte-identical to keep
//     working. Renaming these would silently break runtime behavior rather
//     than just relabel text.
//  2. Rename-history documentation — comments that talk *about* a retired
//     name (e.g. "renamed from Tapfolio") rather than render it as brand
//     copy. Kept as prose, per this project's convention of updating rename
//     history to remain accurate rather than deleting it.
//
// Line-scoped (exact-string), not whole-file: each entry is the literal text
// of the ONE line that's allowed to say an old name. Any other line in the
// same file — including a new offender introduced later — still fails the
// check. (A prior version of this allowlist skipped the entire file, which
// is how app/admin/factory/page.tsx was able to print an unrelated,
// unowned domain that nobody caught until a full-branch audit; see the
// final-review-fixes report.)
const INFRA_EXCEPTIONS: Record<string, string[]> = {
  // localStorage keys for the guest cart id, an applied discount code, and
  // offline-captured leads. Read back by these exact string values from
  // CartContext.tsx / shop/cart/page.tsx / shop/checkout/page.tsx /
  // offline-leads.ts (all of which now import the constants from here
  // instead of holding their own literal) — renaming any of them would
  // orphan a value already written to a real user's browser under the old
  // key before the first rename shipped.
  // Test fixtures that exercise the QR parser against the literal hosts
  // printed on already-shipped cards. Two generations of physical stock
  // carry retired hostnames; the parser must keep accepting them, so the
  // fixtures must keep naming them.
  [join("components", "dashboard", "QrClaimScanner.test.ts")]: [
    '"https://herald-ph.vercel.app",',
    '"https://tapfolio-beta.vercel.app",',
  ],
  [join("lib", "storage-keys.ts")]: [
    'export const GUEST_CART_ID_KEY = "tapfolio_guest_cart_id";',
    'export const DISCOUNT_CODE_KEY = "tapfolio_discount_code";',
    'export const OFFLINE_LEADS_KEY = "tapfolio_offline_leads";',
  ],
  // Rename-history comment in the brand-constants module itself.
  [join("lib", "brand.ts")]: [
    '* captured lead. (Previously "Herald", named for the medieval herald\'s two',
    '* name collided with a live, unrelated company operating as tapfolio.me.)',
  ],
  // Rename-history paragraph in the top-level README.
  [join("README.md")]: [
    'Tagline: "Every tap counts." (Previously named "Herald," after the medieval',
    "herald's duties of announcing a person and designing their coat of arms,",
    "tapfolio.me.)",
  ],
};

test("no user-facing source file still says either retired brand name", () => {
  const selfPath = join("lib", "brand.test.ts");
  const offenders: string[] = [];
  for (const file of walk(process.cwd())) {
    const rel = file.replace(process.cwd(), "").replace(/^[\\/]/, "");
    if (rel === selfPath) continue;
    const allowedLines = INFRA_EXCEPTIONS[rel] ?? [];
    const content = readFileSync(file, "utf8");
    const remaining = content
      .split("\n")
      .filter((line) => !allowedLines.some((allowed) => line.trim() === allowed))
      .join("\n");
    if (STALE_BRAND.test(remaining)) offenders.push(rel);
  }
  expect(offenders, `stale brand in:\n${offenders.join("\n")}`).toEqual([]);
});

// Guard against reintroducing the bug this project has now hit twice: 48 JSX
// call sites hardcoded the CURRENT brand name ("Herald") as a string literal
// instead of importing HERALD from this module, which made the first rename
// (Tapfolio -> Herald) an expensive repo-wide sweep instead of a one-line
// edit here. The second rename (Herald -> SigmaTap) stayed cheap because that
// migration had already happened — this test now protects SigmaTap the same
// way, and fails the day someone types a new `>SigmaTap<` or
// `"...SigmaTap..."` into app/** or components/** instead of
// `{SIGMATAP.name}`.
//
// `\bSigmaTap\b` is deliberately case-sensitive with word boundaries: it
// does NOT match `SigmaTapMark` / `buildSigmaTap` (no boundary between
// "SigmaTap" and the adjoining word character) or `SIGMATAP` /
// `sigmatap-mark.svg` / `--sigmatap-seal` (wrong case) — those are
// legitimate, not brand-string leaks, so they need no allowlist entry at
// all. Only a handful of doc comments that *talk about* the brand name (not
// render it) remain and are allowlisted by exact line below, same
// line-scoped mechanism as INFRA_EXCEPTIONS above.
const CURRENT_BRAND_WORD = /\bSigmaTap\b/;

const NEW_BRAND_STRING_SCAN_DIRS = ["app", "components"];

// Line-scoped exceptions: comment-only mentions of "SigmaTap" that describe
// the mark/design system rather than render brand copy. Deliberately kept
// as prose, not migrated to the constant (rule 2 in the migration task).
const NEW_BRAND_STRING_EXCEPTIONS: Record<string, string[]> = {
  [join("components", "brand", "SigmaTapMark.tsx")]: [
    "* SigmaTap's monogram — a solid Greek sigma. Inlined from the source SVG",
    '*  visible word "SigmaTap" — it\'s then decorative and hidden from the',
    '*  accessibility tree so screen readers don\'t announce "SigmaTap" twice. */',
  ],
  [join("app", "globals.css")]: [
    "/* SigmaTap — enforced scales. Exactly three radii, exactly two elevations. */",
    "/* SigmaTap identity — the sigma struck into a seal disc. Committed color",
  ],
  // Rename-history comment naming both retired stages.
  [join("app", "admin", "factory", "page.tsx")]: [
    "// (Tapfolio -> Herald -> SigmaTap) — this is the real, live Vercel",
  ],
};

test("no new hardcoded occurrence of the current brand name in app/** or components/**", () => {
  const offenders: string[] = [];
  for (const dir of NEW_BRAND_STRING_SCAN_DIRS) {
    const root = join(process.cwd(), dir);
    for (const file of walk(root)) {
      if (!/\.(tsx?|css)$/.test(file)) continue;
      const rel = file.replace(process.cwd(), "").replace(/^[\\/]/, "");
      const allowedLines = NEW_BRAND_STRING_EXCEPTIONS[rel] ?? [];
      const content = readFileSync(file, "utf8");
      const remaining = content
        .split("\n")
        .filter((line) => !allowedLines.some((allowed) => line.trim() === allowed))
        .join("\n");
      if (CURRENT_BRAND_WORD.test(remaining)) offenders.push(rel);
    }
  }
  expect(offenders, `hardcoded "SigmaTap" outside SIGMATAP constant in:\n${offenders.join("\n")}`).toEqual([]);
});
