import type { JSX } from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { BEATS, TOTAL_FRAMES, type BeatId } from "./timeline";
import { CUES, SFX_PREROLL, type Sfx } from "./audio";
import { VO_LINES, duckAt } from "./voiceover";
import { Hook } from "./scenes/Hook";
import { Tap } from "./scenes/Tap";
import { Profile } from "./scenes/Profile";
import { Leads } from "./scenes/Leads";
import { Personas } from "./scenes/Personas";
import { Cta } from "./scenes/Cta";
import { MatchCut } from "./fx/MatchCutLot";

const SCENES: Record<BeatId, () => JSX.Element> = { hook: Hook, tap: Tap, profile: Profile, leads: Leads, personas: Personas, cta: Cta };

/** The composed music bed in video/public/, regenerated by `npm run compose`. */
export const MUSIC: string | null = "music.mp3";
const MUSIC_VOLUME = 0.85;
/** The voiceover level; the music ducks under it (see duckAt). */
const VO_VOLUME = 1;
/** Per-effect level against the music; compose.mjs peak-normalises every file. */
const SFX_VOLUME: Record<Sfx, number> = { whoosh: 0.5, tick: 0.5, chime: 0.4, pop: 0.45, riser: 0.45 };

const FADE_IN = 15;
const FADE_OUT = 60; // music fades out over the last 2 s

export function Showcase() {
  return (
    <AbsoluteFill>
      {BEATS.map((b) => {
        const Scene = SCENES[b.id];
        return (
          <Sequence key={b.id} from={b.from} durationInFrames={b.frames} name={b.id}>
            <Scene />
          </Sequence>
        );
      })}
      {/* The chamfered lot carries each act's key shape across the cut; the scenes switch underneath at the window's midpoint. */}
      <MatchCut />
      {MUSIC && <Audio src={staticFile(MUSIC)} volume={(f) => MUSIC_VOLUME * duckAt(f) * Math.min(1, f / FADE_IN, (TOTAL_FRAMES - f) / FADE_OUT)} />}
      {VO_LINES.map((line) => (
        <Sequence key={line.id} from={line.from} durationInFrames={line.frames} name={`vo-${line.scene}`}>
          <Audio src={staticFile(line.file)} volume={VO_VOLUME} />
        </Sequence>
      ))}
      {/* Each effect starts SFX_PREROLL frames early, so the moment inside the file lands exactly on its cue frame. */}
      {CUES.map((cue) => (
        <Sequence key={`${cue.sfx}-${cue.frame}`} from={Math.max(0, cue.frame - SFX_PREROLL[cue.sfx])} name={`sfx-${cue.sfx}`}>
          <Audio src={staticFile(`sfx-${cue.sfx}.wav`)} volume={SFX_VOLUME[cue.sfx]} />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
}
