import { beat, type BeatId } from "./timeline";
import timing from "./vo-timing.json";

export type VoLine = { id: string; file: string; scene: BeatId; from: number; frames: number };

/** Lines start 0.2 s after the cut, once the whoosh has peaked. */
export const LEAD = 6;
/** The hook has no cut to wait for: its line starts after the caption has appeared. */
export const HOOK_START = 9;

/** The voiceover (Kokoro af_heart), regenerated by `npm run vo`; `from` is an absolute frame. */
export const VO_LINES: VoLine[] = (timing as { id: string; file: string; scene: BeatId; frames: number }[]).map((t) => ({
  ...t,
  from: t.scene === "hook" ? HOOK_START : beat(t.scene).from + LEAD,
}));

/** Music gain while someone is speaking (about -8 dB), and the length of each ramp in frames. */
export const DUCK_GAIN = 0.4;
export const DUCK_RAMP = 6;

const smooth = (t: number) => t * t * (3 - 2 * t);

/** Multiplier for the music at an absolute frame: 1 in the gaps, DUCK_GAIN under a line, eased over DUCK_RAMP frames either side. */
export function duckAt(frame: number): number {
  let gain = 1;
  for (const { from, frames } of VO_LINES) {
    const into = (frame - (from - DUCK_RAMP)) / DUCK_RAMP; // 0 -> 1 across the ramp in
    const out = (from + frames + DUCK_RAMP - frame) / DUCK_RAMP; // 1 -> 0 across the ramp out
    const depth = smooth(Math.max(0, Math.min(1, into, out)));
    gain = Math.min(gain, 1 - (1 - DUCK_GAIN) * depth);
  }
  return gain;
}
